name: adaface
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pytorch
  - pytorch-cuda=12.1
  - torchvision
  - numpy
  - opencv
  - requests
  - flask
  - psutil
  - nvidia-ml-py
